---
  dest: # Compiled files destinations
    templates: 'build/js'
    config: 'build/json'
  src: # Source files (for compiling)
    templates:
      partials:
        display: './src/partials/display/*.body.hbs'
        speech: './src/partials/speech/*.ssml.hbs'
      skills:
        display:
        - './src/skills/**/templates/display/*.body.hbs'
        - './src/skills/**/templates/display/**/*.body.hbs'
        speech:
        - './src/skills/**/templates/speech/*.ssml.hbs'
        - './src/skills/**/templates/speech/**/*.ssml.hbs'
    config: './config/settings.yml'
